;AnnotatePlayback
(define-once AnnotatePlayback::timings '())
(define-once AnnotatePlayback::positions '())

(let ((tag "AnnotationPlayback")(choice #f)(menu '()))
	(define (FindAudioAnnotations)
		(d-MoveToBeginning)
		;(disp "list is " (reverse AnnotatePlayback::timings) " a list? " (list?  AnnotatePlayback::timings))
		(for-each 
			(lambda (thetime)   
				(while (and (d-NextChord) (<= (d-GetMidiOnTime) thetime)))
				(set! AnnotatePlayback::positions (cons (GetPosition) AnnotatePlayback::positions)))
			(reverse AnnotatePlayback::timings)))
			
	(define (InsertAudioAnnotations)
		(d-MoveToBeginning)
		;(disp "pos list is " (reverse AnnotatePlayback::positions) " a list? " (list?  AnnotatePlayback::positions))
		(for-each 
			(lambda (position)   
				(apply d-GoToPosition position)
				(d-DirectivePut-standalone-graphic tag "CrossSign"))
			(reverse AnnotatePlayback::positions)))
			
	(define (DeleteAnnotationMarkers)
				(d-PushPosition)
				(d-MoveToBeginning)
				(while (d-NextObject)
					(d-DirectiveDelete-standalone tag))
				(d-PopPosition))
	(define (PlayContext)
		(d-PushPosition)
		(while (d-NextObjectInMeasure))
		(DenemoSetPlaybackEnd)
		(d-MoveToMeasureLeft)
		(DenemoSetPlaybackStart)
		;(apply d-GoToPosition (GetPosition));gets the start of the bar in view while playing
		(d-Play "(d-PopPosition)"))

;;;;procedure starts here

	(set! menu (list (cons (_ "Play and Annotate") 'annotate)))
	(if (not (null? AnnotatePlayback::positions))
		(begin
			(set! menu (cons (cons (_ "Insert Annotation Markers") 'insert) menu))))
	(set! menu (cons (cons (_ "Move & Play Next Annotation") 'forward) menu))
	(if (d-Directive-standalone? tag)
		(set! menu (cons (cons (_ "Label Annotation") 'label) menu)))	
	(set! menu (cons (cons (_ "Clear Annotation Markers") 'clear) menu))
	(set! menu (cons (cons (_ "Help") 'help) menu))
	(set! choice (TitledRadioBoxMenuList (_ "Playback Annotation") (reverse menu)))
	(case choice
				((annotate)
					(d-PushPosition)		
					(d-DenemoPlayCursorToEnd)
					(set! AnnotatePlayback::timings '())
					(set! AnnotatePlayback::positions '())
					(let loop ()
						(define key (d-GetKeypress))
						(define time (d-AudioIsPlaying))
						(if (and time (equal? key "space"))
							(begin
								(set! AnnotatePlayback::timings (cons  time  AnnotatePlayback::timings))
								(loop))))
					(d-Stop)
					;(disp  "Timings " AnnotatePlayback::timings "\n")
					(FindAudioAnnotations)
					(set! AnnotatePlayback::positions (reverse  AnnotatePlayback::positions))
					(d-PopPosition))
				((insert)
					(InsertAudioAnnotations)
					(set! AnnotatePlayback::positions '()))
				((clear)
					(DeleteAnnotationMarkers))
				((label)
					(if (d-Directive-standalone? tag)
						(d-DirectivePut-standalone-display tag (d-GetUserInput (_ "Give label for this annotation")))))				
				((forward)
					(while (and (d-NextObject) (not (d-Directive-standalone? tag))))
					(if (d-Directive-standalone? tag)
						(PlayContext)
						(d-InfoDialog (_ "No more Playback Annotations markers"))))
				((help)
					(d-InfoDialog (_ "This command allows you to mark moments during playback for further study.\nChoosing Play and Annotate allows you to mark moments as you listen by pressing the space bar. Pressing any other key stops the play.\nLaunch the command again and choose Insert Annotation Markers to insert marks \"x\" into the current staff.\nThen launch the command once more to play a couple of bars at the next annotation - you can label the mark with a comment, edit the score etc, before moving on to the next.\nMarks can be deleted just like any other object or the Clear All Marks option can be chosen to finish.")))))
